# from http://conda.pydata.org/docs/travis.html
language: python
dist: trusty
env:
  - CVXPY_VERSION=0.4.9
  - CVXPY_VERSION=1.0.1
python:
   - "3.4"
   - "3.5"
   - "3.6"
# fix for https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip flake8
    pytest-cov conda-build anaconda-client conda-verify
  - conda install -q -n test-environment -c conda-forge lapack
  - conda install -q -n test-environment -c cvxgrp cvxpy=$CVXPY_VERSION
 
  - source activate test-environment
  # pip install coveralls since conda only has > 3.5
  - pip install coveralls
  - python setup.py install

# command to run tests
script:
  - flake8 mapping
  - pytest mapping/tests -v --cov=mapping --cov-report term-missing
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.5" ]; then conda-build --no-anaconda-upload .; fi

after_success:
  - coveralls
  - if [[ "$TRAVIS_TAG" && "$CVX_VERSION" == "1.0.1" && "$TRAVIS_PYTHON_VERSION" != "3.5" ]];
    then echo "Uploading $(conda build . --output) to anaconda cloud"; fi
  - if [[ "$TRAVIS_TAG" && "$CVX_VERSION" == "1.0.1" && "$TRAVIS_PYTHON_VERSION" != "3.5" ]];
    then anaconda -t $CONDA_UPLOAD_TOKEN upload $(conda build . --output); fi

notifications:
  email: false

deploy:
  provider: pypi
  user: matthewgilbert
  password:
    # generate from terminal using "travis encrypt PYPI_PW -r user/repo"
    secure: "2lauoQXYE1PzPrcTVmcyGjTPTnd3Nd2EWQvSZ9SrEizOmNaZqavpELQiKJLkuy04BxXBBhGNukw9X12Za75K7w7+8IkLWndc824AWkTiQrERts8rsd0rfV6f3nCTUFlEzOIYMOT+wW2TDzZhsqvBWSJfYYkLp3blN0zub0vwFfelS6lOkAVkLbTO1VZ6LM3SB4/RfnQoEPu0LTN4ucZsCLZogFSE5koqCk+CuyXajgmw6HJDuRh08GIm9OkGa5D+hnQOu962Qd1AHOIzeNs0bYINe7atm2HFmt2OTZ3QoBZdvne2htShImXRJ3kOd1mBK4B7WA18AFAebogtp/P3c5hCG14IzPJxl9wsdOK367eYAUiPLEauWn6IV/AHK1ZXAvUrjT+b76wI7hOrT5TNOfhEn+pEyyYLyq1b7dF82krT1QpwnIzPXsOXd5Pc4YEUTNIq42iA5OnbR/2NRQx3qf/lM6m3pacW9LtDzv3RlqLZpUVcIbI09WtOHu51G/wClYaWlxg5GvPmEpiHTTJFQkv8E9BsbBNXeGs4F6c3E8GqpOpoV57GFKP4Txa7vG7Rg827tOzf5mhirIzaq+QD6klLve5hopbRr0NZSywRZiQe59w0xy5zoV2nfQnm1e1NyLFduCjyiDWTxuy9J7325y81jFvDybgWfRFTXswlfG4="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: matthewgilbert/mapping
    branch: master
    condition: $CVXPY_VERSION == 1.0.1 && $TRAVIS_PYTHON_VERSION == 3.7
