# from http://conda.pydata.org/docs/travis.html
language: python
dist: trusty
env:
  - CVXPY_VERSION=0.4.9
  - CVXPY_VERSION=1.0.1
python:
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.6-dev" # 3.6 development branch
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls flake8 pytest-cov
  - conda install -q -n test-environment -c conda-forge lapack
  - conda install -q -n test-environment -c cvxgrp cvxpy=$CVXPY_VERSION
  - source activate test-environment
  - python setup.py install
# command to run tests
script:
  - flake8 mapping
  - pytest mapping/tests -v --cov=mapping --cov-report term-missing
after_success:
  coveralls
# Don't want notifications
notifications:
  email: false