language: python
dist: trusty
python:
# 2.7 not currently supported
#   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.6-dev" # 3.6 development branch
before_install:
  - sudo apt-get update
  # needed to install cvxpy
  - sudo apt install cmake
install:
  - "pip install -r dev-requirements.txt"
# command to run tests
script:
  - flake8 mapping
  - pytest mapping/tests -v --cov=mapping --cov-report term-missing
after_success:
  coveralls
# Don't want notifications
notifications:
  email: false