package:
    name: mapping
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

requirements:
  host:
    - cvxpy
    - numpy
    - pandas
    - python
    - pip
  run:
    - cvxpy
    - numpy
    - pandas
    - python

# testing reference
# https://github.com/conda-forge/conda-forge.github.io/issues/345
test:
  requires:
    - pytest
  imports:
    - mapping
    - mapping.tests
  commands:
    - pytest --pyargs mapping

about:
  home: https://github.com/matthewgilbert/mapping
  license: MIT
